--- 
- name: installing lampstack webservers
  become: yes
  hosts: webserver
  tasks:
    - name: installing apache
      package:
        name: "{{ package_name }}"
        state: present
    - name: installing php packges
      package: 
          name: "{{ item }}"
          state: present
      loop: "{{ php_packages }}"
    - name: copying info.php from local to ansible nodes
      copy:
        src: info.php
        dest: /var/www/html/info.php  
    - name: starting and enabling the service
      service:
           name: "{{ package_name}}"
           state: started
           enabled: yes
