---
- name: testing include task
  hosts: all
  become: no
  gather_facts: no
  tasks:
    - name: main task
      debug:
        msg: "see what happens"
      register: fist_results
    - include: more-tasks.yaml
