---
- name: "first yaml file"
  become: yes
  hosts: all
  tasks:
    - name: "installing java"
      apt:
        - name: apache2
          update_cache: yes
          state: present

    - name: "install php"
      apt:
        - name: php
          state: present
    - name: "install apache libraries"
      apt:
        - name: libapache2-mod-php
          state: present
    - name: "install php-mysql"
      apt:
        - name: php-mysql
          state: present
    - name: "install php-cli"
      apt:
        - name: php-cli
          state: present
    - name: "copying info.php from local to ansible nodes"
      copy:
        src: info.php
        dest: /var/www/html/info.php
