---
- name:  first yaml file
  become: yes
  hosts: all
  tasks:
    - name: installing java
      apt:
        - name: apache2
          update_cache: yes
          state: present
    - name: installing php_packages
      apt:
        - name: "{{ item }}"
          state: present 
      loop:
        - php 
        - libapache2-mod-php
        - php-mysql
        - php-cli 