---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-demo
spec:
  rules:
   - http:
      paths:
       - backend:
           serviceName: jenkins-svc
           servicePort: 80
         path: 
       - backend:
           serviceName: gol-svc
           servicePort: 80
         path: /gameoflife    