---
- name: installing the tomcat
  become: yes
  hosts: webserver
  var_files:
    - varfile.yaml
  tasks:
    - name: installing java
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes
      when: ansible_facts ['distribution'] == "Ubuntu"

    - name: adding group
      group:
        name: "{{ username }}"
        state: present

    - name: adding the user
      user:
        name: "{{ username }}"
        home: "{{ path }}"
        state: present
        shell: /bin/false
        group: "{{ username }}"

      when: ansible_facts ['distribution'] == "Ubuntu"
    - name: make sure unzip is available
      package:
        name: unzip
        state: present
    - name: download the tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "{{ tomcat_dest }}"
      when: ansible_facts ['distribution'] == "Ubuntu"
    - name: unziping
      unarchive:
        src: "{{ tomcat_dest }}"
        dest: "{{ path }}"
      when: ansible_facts ['distribution'] == "Ubuntu"
      notify:
        - create symbolic link
    - name: chaning the ownership recursive
      file:
        path: "{{ path }}"
        recurse: yes
        owner: tomcat
    - name: giving execute permission
      file:
        path: "{{ item }}"
        mode: "+x"
      loop: "{{ tomcat_excutables }}"

    - name: copying file
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      notify:
        - starting daemon

  handlers:
    - name: create symbolic link
      file:
        src: /opt/tomcat/apache-tomcat-8.5.61
        dest: "{{ tomcat_path }}"
        state: link
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: starting daemon
      systemd:
        name: tomcat
        daemon_reload: yes
        state: started
