---
apiVersion : v1
kind       : Pod
metadata : 
    name : gol-pod
spec:
   containers:
      - name : game-of-life
        image: anilreddy273/crazymind:21012020
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "750m"
        livenessProbe:
           httpGet:
             path: /gameoflife
             port: 8080

           timeoutSeconds: 4 
           initialDelaySeconds: 10
           periodSeconds: 15
           successThreshold: 2
           failureThreshold: 3
        ports:
          - containerPort : 8080
            name: golport
            protocol: TCP