---
apiVersion : apps/v1
kind: ReplicaSet
metadata:
   name: gol-rs
spec:
   replicas : 2
   minReadySeconds: 5
   selector:
     matchLabels:
       app : gol
       version: 07112020
   template:
     metadata:
       labels:
         app: gol
         version: 07112020
     spec:
       containers:
         - name : gol
           image: qualitythought/gameoflife:07112020
           ports:
             - containerPort : 8080
               name: golhttp
               protocol: TCP