---
apiVersion : v1
kind       : Pod
metadata : 
    name : gol-pod
spec:
   containers:
      - name : game-of-life
        image: anilreddy273/crazymind:21012020
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "750m"
        ports:
          - containerPort : 8080
            name: golport
            protocol: TCP