---
apiVersion: v1
kind: PersistentVolume
metadata: 
   name: pv-test
spec:
  capacity:
    storage: 1Gi
  accessModes: 
     - ReadWriteOnce
  storageClassName: slow
  awsElasticBlockStore:
    volumeID: vol-00be152e19c226c10 
    fsType: ext4
