---
apiVersion: v1
kind: 
metadata:
   name: test-vol
spec:
  containers:
    - name: gol
      image: qualitythought/gameoflife:07112020
      ports:
        - conatinerPort: 8080
          name: gol-port
          protocol: TCP
      volumeMounts:
        - mountPath: /webapps
          name: pvc-try 
  volumes:
    - name: pvc-try
      PersistentVolumeClaim: 
        claimName: test-pvc

