pipeline { 
    agent { label 'HRMS&&QA' }
    triggers{ pollSCM( '* * * * *' ) }
    stages{
        stage("input of user"){
            steps{
                input message: "do you want to continue?"
            }
        }
        stage("git"){
            steps{
                git "https://github.com/wakaleo/game-of-life.git"
            }
        }
        stage("build"){
            steps{
                sh 'mvn clean package'
            }
        }
       
    }
    
}