pipeline { 
    agent { label 'HRMS&&QA' }
    triggers{ pollSCM( '* * * * *' ) }
    parameters{
        string(name: 'DEPLOY_ENV', defaultValue: 'staging', description: 'which environment')
        text(name: 'DEPLOY_TEXT', defaultValue: 'One\nTwo\nThree\n', description: '')
        booleanParam(name: 'DEBUG_BUILD', defaultValue: true, description: '')
        choice(name: 'CHOICES', choices: ['one', 'two', 'three'], description: '')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'A secret password')

    }
    stages{
        stage("input of user"){
            steps{
                input message: "do you want to continue?"
            }
        }
        stage("git"){
            steps{
                git "https://github.com/wakaleo/game-of-life.git"
            }
        }
        stage("build"){
            steps{
                sh 'mvn clean package'
            }
        }
       
    }
    
}